#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# EAS Station — Postal Mail Server Setup
# ─────────────────────────────────────────────────────────────────────────────
# Runs once to:
#   1. Generate secrets and write postal/.env + postal/postal.yml
#   2. Pull images and start MariaDB / RabbitMQ
#   3. Initialize the Postal database
#   4. Create the Postal admin user
#   5. Start all Postal services
#   6. Print the SMTP URL to paste into EAS Station Notification Settings
#
# Usage:
#   sudo bash scripts/setup_postal.sh
#
# Re-running the script is safe; it skips steps that are already done.
# ─────────────────────────────────────────────────────────────────────────────

set -euo pipefail

# ── Paths ─────────────────────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
POSTAL_DIR="${REPO_ROOT}/postal"
ENV_FILE="${POSTAL_DIR}/.env"
CONFIG_FILE="${POSTAL_DIR}/postal.yml"
CONFIG_EXAMPLE="${POSTAL_DIR}/postal.yml.example"

# ── Colours ───────────────────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

info()    { echo -e "${CYAN}[postal]${NC} $*"; }
success() { echo -e "${GREEN}[postal]${NC} $*"; }
warn()    { echo -e "${YELLOW}[postal]${NC} $*"; }
error()   { echo -e "${RED}[postal] ERROR:${NC} $*" >&2; }
fatal()   { error "$*"; exit 1; }
banner()  { echo -e "\n${BOLD}${CYAN}══════════════════════════════════════════${NC}"; \
            echo -e "${BOLD}${CYAN}  $*${NC}"; \
            echo -e "${BOLD}${CYAN}══════════════════════════════════════════${NC}\n"; }

# ── Helpers ───────────────────────────────────────────────────────────────────
gen_secret() {
    # 48 random bytes → 64-char hex string, no special chars → safe for YAML/env
    openssl rand -hex 48 2>/dev/null || cat /dev/urandom | tr -dc 'a-f0-9' | head -c 96
}

require_cmd() {
    command -v "$1" &>/dev/null || fatal "'$1' is not installed. Please install it first."
}

compose_cmd() {
    # Prefer 'docker compose' (v2); fall back to 'docker-compose' (v1)
    if docker compose version &>/dev/null 2>&1; then
        docker compose --project-directory "${POSTAL_DIR}" "$@"
    else
        docker-compose --project-directory "${POSTAL_DIR}" "$@"
    fi
}

wait_for_port() {
    local host="$1" port="$2" label="$3" retries="${4:-30}"
    info "Waiting for ${label} on ${host}:${port}…"
    for i in $(seq 1 "${retries}"); do
        if bash -c ">/dev/tcp/${host}/${port}" 2>/dev/null; then
            success "${label} is ready."
            return 0
        fi
        sleep 2
    done
    fatal "${label} did not become ready in time."
}

# ── Preflight ─────────────────────────────────────────────────────────────────
banner "EAS Station — Postal Setup"

require_cmd docker
require_cmd openssl

if ! docker info &>/dev/null; then
    fatal "Docker daemon is not running (or current user cannot access it)."
fi

# ── Step 1: Generate secrets ──────────────────────────────────────────────────
if [[ -f "${ENV_FILE}" ]]; then
    warn ".env already exists — skipping secret generation (delete postal/.env to regenerate)."
    # shellcheck source=/dev/null
    source "${ENV_FILE}"
else
    info "Generating secrets…"
    POSTAL_DB_ROOT_PASSWORD="$(gen_secret)"
    POSTAL_DB_PASSWORD="$(gen_secret)"
    POSTAL_RABBITMQ_PASSWORD="$(gen_secret)"
    RAILS_SECRET_KEY="$(gen_secret)"

    cat > "${ENV_FILE}" <<EOF
# Postal secrets — generated by setup_postal.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# DO NOT commit this file to source control.
POSTAL_DB_ROOT_PASSWORD=${POSTAL_DB_ROOT_PASSWORD}
POSTAL_DB_PASSWORD=${POSTAL_DB_PASSWORD}
POSTAL_RABBITMQ_PASSWORD=${POSTAL_RABBITMQ_PASSWORD}
RAILS_SECRET_KEY=${RAILS_SECRET_KEY}
EOF
    chmod 600 "${ENV_FILE}"
    success "Secrets written to postal/.env"
fi

# ── Step 2: Write postal.yml from template ────────────────────────────────────
if [[ -f "${CONFIG_FILE}" ]]; then
    warn "postal/postal.yml already exists — skipping config generation."
else
    info "Writing postal/postal.yml from template…"

    # Source .env if not already done
    # shellcheck source=/dev/null
    [[ -z "${POSTAL_DB_PASSWORD:-}" ]] && source "${ENV_FILE}"

    sed \
        -e "s|POSTAL_DB_PASSWORD_PLACEHOLDER|${POSTAL_DB_PASSWORD}|g" \
        -e "s|POSTAL_RABBITMQ_PASSWORD_PLACEHOLDER|${POSTAL_RABBITMQ_PASSWORD}|g" \
        -e "s|RAILS_SECRET_KEY_PLACEHOLDER|${RAILS_SECRET_KEY}|g" \
        "${CONFIG_EXAMPLE}" > "${CONFIG_FILE}"

    chmod 600 "${CONFIG_FILE}"
    success "postal/postal.yml written."
fi

# ── Step 3: Pull images ───────────────────────────────────────────────────────
info "Pulling Postal Docker images (this may take a few minutes)…"
compose_cmd pull

# ── Step 4: Start dependencies (MariaDB + RabbitMQ) ──────────────────────────
info "Starting MariaDB and RabbitMQ…"
compose_cmd up -d postal-mariadb postal-rabbitmq

info "Waiting for database health checks to pass…"
# Docker healthcheck polls; we also do a direct port check as belt-and-braces
wait_for_port 127.0.0.1 3306 "MariaDB" 45
wait_for_port 127.0.0.1 5672 "RabbitMQ" 45

# ── Step 5: Initialize Postal database ────────────────────────────────────────
# The initialize command is idempotent — safe to run again.
info "Initializing Postal database (runs migrations)…"
compose_cmd run --rm postal-web postal initialize

# ── Step 6: Create admin user ─────────────────────────────────────────────────
banner "Create Postal Admin User"
echo -e "${YELLOW}You will now be prompted to enter credentials for the Postal web UI admin account.${NC}"
echo -e "${YELLOW}Remember these — you will use them to log in at http://localhost:5000${NC}\n"
compose_cmd run --rm postal-web postal make-user

# ── Step 7: Start all services ────────────────────────────────────────────────
info "Starting all Postal services…"
compose_cmd up -d

wait_for_port 127.0.0.1 5000 "Postal web UI" 30
wait_for_port 127.0.0.1 2525 "Postal SMTP"   30

# ── Step 8: Enable systemd service (if available) ─────────────────────────────
SYSTEMD_SERVICE="/etc/systemd/system/eas-station-postal.service"
if [[ -f "${REPO_ROOT}/systemd/eas-station-postal.service" ]] && command -v systemctl &>/dev/null; then
    info "Installing systemd service…"
    cp "${REPO_ROOT}/systemd/eas-station-postal.service" "${SYSTEMD_SERVICE}"
    # Patch the WorkingDirectory to this repo's postal/ subdirectory
    sed -i "s|__POSTAL_DIR__|${POSTAL_DIR}|g" "${SYSTEMD_SERVICE}"
    systemctl daemon-reload
    systemctl enable eas-station-postal
    success "eas-station-postal.service enabled (starts Postal on boot)."
fi

# ── Step 9: Print next steps ──────────────────────────────────────────────────
banner "Setup Complete"

cat <<INSTRUCTIONS
${BOLD}Next steps:${NC}

  1. Open the Postal web UI:
     ${CYAN}http://localhost:5000${NC}

  2. Log in with the admin credentials you just created.

  3. Create an Organisation (e.g. "EAS Station").

  4. Inside the organisation, create a Mail Server (e.g. "eas-alerts").

  5. Under the mail server → Credentials, create an SMTP credential.
     Note the generated ${BOLD}username${NC} and ${BOLD}password${NC}.

  6. Configure your sending domain under the mail server → Domains tab,
     and follow the DNS instructions (SPF, DKIM, MX).

  7. In EAS Station → Settings → Notifications, enter the Mail Server URL:

     ${CYAN}smtp://<username>:<password>@localhost:2525${NC}

     Or use the "Use Local Postal" button in the Notifications admin panel —
     it will detect that Postal is running and pre-fill the host/port for you.

${BOLD}Useful commands:${NC}
  View logs:    docker compose --project-directory ${POSTAL_DIR} logs -f
  Stop Postal:  systemctl stop  eas-station-postal   (or: docker compose … down)
  Start Postal: systemctl start eas-station-postal

INSTRUCTIONS
